### ISSUE TITLE
Switch from LDAP to Auth0

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#12]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1447356

* [x] Release kinto 8.2.0 with OpenID support
* [x] Ask Ops to create an Auth0 setup for Stage and Prod https://bugzilla.mozilla.org/show_bug.cgi?id=1447355 
* [x] Create STAGE/PROD Remote Settings configs on Auth0
* [x] Deploy new version of kinto-admin/kinto/kinto-dist with OpenID support
* [x] Add OpenID in Kinto-Admin #1
* [x] Deploy a version with support of OpenID in Kinto Admin (without enabling it)
* [x] Enable internal accounts feature #24
* [x] Switch cloudservice user to internal account user #24 / https://bugzilla.mozilla.org/show_bug.cgi?id=1447347
* [x] Verify that cloudservice user works
* [x] Enabled OpenID : Replace LDAP policy by OpenID on server (cloudops repo). Using `ldap` as the auth policy name and `email` as the user id field won't require any permission change.

```ini
kinto.includes = ...
                 kinto.plugins.accounts
                 kinto.plugins.openid
multiauth.policies = account ldap 
multiauth.policy.account.use = kinto.plugins.accounts.authentication.AccountsAuthenticationPolicy
# Using OpenID with `ldap` as a policy id prevents us from migrating permissions since userids will still be prefixed with `ldap:`
multiauth.policy.ldap.use = kinto.plugins.openid.OpenIDConnectPolicy
```

**Comment by peterbe** [comment]
@leplatrem I'm actually stumped about what the service for this is. 
You just need creds for local development (client id and client secret). 
What they need in https://mozilla.service-now.com/sp?id=sc_cat_item&sys_id=1e9746c20f76aa0087591d2be1050ecb is a couple of URLs.
And I'm not sure what to fill out and the more I look at the form the simpler it seems (except it's not clear how you select *multiple* people to email the encrypted creds to). 

* What's the URL? For Dev you can enter two, e.g. https://settings-admin.dev.mozaws.net/ AND http://localhost:8888 that way you can use it when you run your kinto server on :8888
* For the callback URL, when you use `mozilla-django-oidc` you use `/oidc/callback/`. Not sure what this would be for kinto.
* As for logout URL, you can just use `/?signedout=true` or something. 
* As for "Which login options would you like to support?" I think you pick only LDAP which effectively is Google for us but it means people can't log in, using Google, with their personal Gmail accounts.

**Comment by leplatrem** [comment]
Thanks for helping on this :) 

Look for dev it would be:

* URL: https://kinto-writer.stage.mozaws.net/v1/admin/ (landing+callback)
   ... and http://localhost:8888/v1/admin/ can be cool indeed!
* The redirect URL on the server will be `http://${server}/v1/openid/ldap/token?`
* We don't have any logout URL in Kinto (yet?) but put `http://${server}/v1/openid/ldap/logout` and we can add it later :)
* We want Google (/Mozilla)

For stage and prod, we want **LDAP only** and the URL are those *Kinto Admin (RW)* from this page: https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=66655528 

> I couln't tell if you were suggesting that I'd do it myself :D

**Comment by leplatrem** [comment]
Update: OPS were emailed the client id/secret for Auth0 on remote-settings STAGE/PROD

**Comment by leplatrem** [comment]
WIP https://github.com/mozilla-services/cloudops-deployment/pull/2283/files

**Comment by leplatrem** [comment]
Done!
