### ISSUE TITLE
Migrate CI/CD pipeline from CircleCI to Github Actions

### ISSUE THREAD

**Issue by grahamalama** [mozilla/remote-settings#475]
```[tasklist]
### Tasks
- [ ] https://github.com/mozilla/remote-settings/pull/477
- [x] Update brach protection to reference GHA CI checks (instead of CIrcle)
- [ ] https://github.com/mozilla/remote-settings/pull/478
- [ ] https://github.com/mozilla/remote-settings/pull/482
- [ ] https://github.com/mozilla/remote-settings/issues/489
```

**Comment by leplatrem** [comment]
This was done 💯

**Comment by grahamalama** [comment]
@leplatrem I'm going to reopen this since I want to consider it done when we publish directly to the GAR (I have it as an open issue in the task list above)
